### PR TITLE
Request and outdated switch

### PR DESCRIPTION
**Pull request by Marsup**
Hey @dtao,

So as discussed on twitter, I'm making that PR to include `request` instead of pure http.
I haven't tested behind a proxy since I'm outside of work but it shouldn't be a problem I hope.

I have combined this pull request with something else I thought would be useful for deft, that is a switch to look for newer versions than those defined in the configuration based on tags, I can't think of anything for other type of definitions.

I'm completely new to jsdoc so sorry if I made any mistake in that.

I hope it doesn't bother you that I bundled the 2 commits in the same PR.

Cheers.

### CODE REVIEW

**Comment by Marsup** [comment]
I might advise you to look at the diff with `?w=1` if you don't want to be bothered by all these indentation changes :)

**Comment by Marsup** [comment]
Confirmed to be working behind proxy.

**Comment by Marsup** [comment]
@dtao Did you have a look at it yet ? I'd love a npm publish with that.

**Comment by dtao** [comment]
Thanks! I'll aim to publish a new version this evening.

**Comment by dtao** [comment]
Well, took me slightly longer than promised, but the new version is finally published. Thanks again!

**Comment by Marsup** [comment]
You're very welcome ! I should have warned you about the other PR I had in mind (and just did), could have slipped it in the same release :(

**Pull request merged**
