### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by Marsup**
Tested this on both linux and windows, because I do have colleagues that work on windows :)

I have removed the use of the unzip binary for a pure node.js module (bower's), it seems to perform just as well.

I also fixed 2 problems :
- if you only had archive dependency, it would fail to create the destination
- wait for copyFile to finish before cleaning up the source

### CODE REVIEW

**Comment by dtao** [comment]
Thanks!

I refactored a little bit, but I will test on a Windows VM before publishing the next version.

**Comment by Marsup** [comment]
I already did but feel free to do so.
I'll refactor next time, didn't want to put too many moving parts in this PR ;)

**Comment by Marsup** [comment]
What would you think of adding hooks for travis and appveyor ?
I just had a look at the latter, configuration is weird (eg: https://github.com/approvals/Approvals.NodeJS/blob/master/appveyor.yml) but if it does the job...

**Comment by dtao** [comment]
Oh, I know you tested on Windows. I just want to make sure my reckless refactoring didn't break your work!

Hooks: absolutely. Given that the idea behind deft is to support application developers, integration with the actual tools and services we use will be crucial to ensuring it's worthwhile. You're thinking for projects with front-end/end-to-end tests, e.g. using Selenium? For unit tests or integration tests alone, I would generally expect deft to be unnecessary as front-end dependencies probably don't need to be loaded.

I definitely _also_ want to integrate with services like Heroku, AppHarbor, etc. where developers actually host their applications. In fact I've got started on a [buildpack](https://github.com/dtao/deft-buildpack-ruby) for Heroku... which I haven't tested at all.

**Comment by Marsup** [comment]
I didn't think so far, I was suggesting you might be interested in setting up CI for deft itself on travis for linux and appveyor for windows.

**Comment by Marsup** [comment]
@dtao ping ?

**Pull request merged**
